name: MuaCoinUI
main: MuaZcoin\DoiTien\Main
api:
 - 3.0.0
 - 3.2.0
version: 3.5
author: BlackPMFury
description: "Mua Coin và Xu"
commands:
 muazcoin:
  description: "Buy ZCoun or Money"
  default: true